// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLNslmYmmYJwnSCZKvaOyi3YHl9E57dM',
    appId: '1:479009358091:web:a50ee9d497e68d7b73e20e',
    messagingSenderId: '479009358091',
    projectId: 'whatsapp-backend-50b98',
    authDomain: 'whatsapp-backend-50b98.firebaseapp.com',
    storageBucket: 'whatsapp-backend-50b98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfsn6uiAyMZpb_LlWzpkPViFpUoQVb1X0',
    appId: '1:479009358091:android:4323d27ad9cd9f6a73e20e',
    messagingSenderId: '479009358091',
    projectId: 'whatsapp-backend-50b98',
    storageBucket: 'whatsapp-backend-50b98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxuUmcFX68xxHoDeCRsSPw5-PX0DToBI',
    appId: '1:479009358091:ios:b6dfc3de3651119273e20e',
    messagingSenderId: '479009358091',
    projectId: 'whatsapp-backend-50b98',
    storageBucket: 'whatsapp-backend-50b98.appspot.com',
    iosBundleId: 'com.example.whatsappCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxuUmcFX68xxHoDeCRsSPw5-PX0DToBI',
    appId: '1:479009358091:ios:b6dfc3de3651119273e20e',
    messagingSenderId: '479009358091',
    projectId: 'whatsapp-backend-50b98',
    storageBucket: 'whatsapp-backend-50b98.appspot.com',
    iosBundleId: 'com.example.whatsappCloneFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQLNslmYmmYJwnSCZKvaOyi3YHl9E57dM',
    appId: '1:479009358091:web:7cecafe4d532dc8573e20e',
    messagingSenderId: '479009358091',
    projectId: 'whatsapp-backend-50b98',
    authDomain: 'whatsapp-backend-50b98.firebaseapp.com',
    storageBucket: 'whatsapp-backend-50b98.appspot.com',
  );
}
